### ISSUE TITLE
Decrypt9 freezes with big xorpads

### ISSUE THREAD

**Issue by motezazer** [archshift/Decrypt9#13]
It's perhaps a New 3DS issue, but when generating big xorpads (3492 MB here), Decrypt9 freezes (no percentage, file size when powering off is 0 bytes).

**Comment by archshift** [comment]
Can you tell me to reopen this if you still have the issue?

**Comment by motezazer** [comment]
It works with latest commit. Thanks!
Now I can generate Xenoblade Chronicles xorpads.
