### ISSUE TITLE
Pony Pets 3D (Japan) failed to decrypt

### ISSUE THREAD

**Issue by ghost** [archshift/Decrypt9#32]
This game has been set NCCH Flags Index[3]=0 [4]=0x01 [5]=0x3 [6]=0 [7]=0x20
That's means using the Original NCCH key and Seed crypto.
It was required a generated using SEEDKeyY and Keyslots 0x2C .exefs_7x.xorpad.
so, I hope ncchinfo_gen.py fixed add the entry in .exefs_7x.xorpad.

ncchinfo_gen.py log here
http://pastie.org/10296440

**Comment by d0k3** [comment]
I think the main problem here is that this game uses the SEED crypto but not keyslot 0x25, which seems to be a rare combination. Responsible is either the ncchinfo_gen.py script, the xorpad generator in Decrypt9 or both.

**Comment by ghost** [comment]
I'll fixed in #34

**Comment by ghost** [comment]
Merged in #35. so, closed.
