### ISSUE TITLE
Cant Open decryt9 with safehax

### ISSUE THREAD

**Issue by masamune99** [archshift/Decrypt9#49]
I use the New phailec guide my firmware is 11.0.0.33 , everything works fine, the homebrew channel , the GBA emu , Doom etc. , But safehax freezes!!. It

**Comment by Ketchup901** [comment]
>It

Are you experencing a stroke?

**Comment by d0k3** [comment]
Github issues is not for support. Safehax is known to work fine. I suggest you properly read the guide.
