### ISSUE TITLE
No support for titles where size => 4GB

### ISSUE THREAD

**Issue by ssbmcortex** [archshift/Decrypt9#5]
Technically not an issue with the program but a limitation of FAT32.
Solution would be to load split file images and output the xorpads in 2GB chunks.

**Comment by Normmatt** [comment]
or if size is 4GB just remove 1byte.

**Comment by archshift** [comment]
I'm not sure this is actually an issue since there's no way for any of the xorpads to be 4+GB, and we don't load the entire roms, just a helper file.
