### ISSUE TITLE
Just restarts to home menu.

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [archshift/Decrypt9#50]
I've tried to run Decrypt9 from the homebrew menu, but it just reboots to the home menu.

I have Decrypt9UI in sd:/3ds/Decrypt9UI

Using Luma3DS 9.0, and the Homebrew Launcher v2.0.0.

**Comment by archshift** [comment]
Sorry, but D9 is effectively abandoned. See https://github.com/d0k3/Decrypt9WIP for a fork that's gotten more love.
